version: '3'

services:

  # sync s3 back to this repo to avoid hash changes for dist files
  # to fix this error: https://github.com/dxpr/dxpr_satis/issues/4
  s3-sync-back:
    image: dxpr/s3cmd
    build:
      context: ./hack/s3cmd
    working_dir: /src
    command: sync --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY -r --delete-removed s3://$AWS_BUCKET/ web/
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET
    volumes:
      - .:/src
      - ./web:/src/web

  build:
    image: ${SATIS_IMAGE:-composer/satis:latest}
    working_dir: /src
    command: build satis.json web/8 --no-interaction -vv
    tty: true
    volumes:
      - .composer:/composer
      - .:/src
      - .ssh:/root/.ssh

  publish:
    image: dxpr/s3cmd
    build:
      context: ./hack/s3cmd
    working_dir: /src
    command: sync --access_key=$AWS_ACCESS_KEY_ID --secret_key=$AWS_SECRET_ACCESS_KEY -r --delete-removed web/8 s3://$AWS_BUCKET/
    tty: true
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_BUCKET
    volumes:
      - .:/src

  invalidate-cache:
    image: amazon/aws-cli
    tty: true
    command: cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths /$DRUPAL_ENDPOINT/packages.json /$DRUPAL_ENDPOINT/index.html
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - DISTRIBUTION_ID
      - DRUPAL_ENDPOINT
